### PR TITLE
1st version with results

### PR DESCRIPTION
**Pull request by xmnlab**
In this PR

- improved structure
- added more expressions for benchmark
- added results (json and chart)
- benckmark just for time execution (mean of a measurement of 3 executions)
- Improved pandas expression
- Added initial html report

### CODE REVIEW

**Comment by xmnlab** [comment]
@dharhas 

1. should we add a benchmark for memory consumption?
2. should the measure for pandas operations consider the data load to memory?

**Comment by xmnlab** [comment]
3. should we generate a html or pdf file like a report with this benchmark?

**Comment by dharhas** [comment]
> @dharhas
> 
> 1. should we add a benchmark for memory consumption?
> 2. should the measure for pandas operations consider the data load to memory?

For 1., I would say yes. For 2. I think it would be valuable to show the total time as well as the fraction it took to load data. so yes.

for 3. I think we should plan on an html report.

**Comment by xmnlab** [comment]
first version of the report

ibis-benchmark

**Comment by xmnlab** [comment]
It seems the dataset I was using is incomplete .
I am checking here the new dataset and if it is complete I will push the result for the complete data.

**Pull request merged**
